// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aliases.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAliasesByAlias = `-- name: CountAliasesByAlias :one
SELECT COUNT(*) FROM product_aliases WHERE alias = ? COLLATE NOCASE
`

func (q *Queries) CountAliasesByAlias(ctx context.Context, alias string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAliasesByAlias, alias)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAliasesByAliasExcept = `-- name: CountAliasesByAliasExcept :one
SELECT COUNT(*) FROM product_aliases WHERE alias = ? COLLATE NOCASE AND product_id != ?
`

type CountAliasesByAliasExceptParams struct {
	Alias     string
	ProductID int64
}

func (q *Queries) CountAliasesByAliasExcept(ctx context.Context, arg CountAliasesByAliasExceptParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAliasesByAliasExcept, arg.Alias, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAlias = `-- name: DeleteAlias :execrows
DELETE FROM product_aliases WHERE id = ?
`

func (q *Queries) DeleteAlias(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlias, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const dropConflictingAliases = `-- name: DropConflictingAliases :exec
DELETE FROM product_aliases
WHERE product_aliases.product_id = ?1
  AND (
    product_aliases.alias = ?2 COLLATE NOCASE
    OR EXISTS (
      SELECT 1 FROM product_aliases AS k
      WHERE k.product_id = ?3
        AND k.alias = product_aliases.alias COLLATE NOCASE
        AND (
          (k.story_id IS NULL AND product_aliases.story_id IS NULL)
          OR k.story_id = product_aliases.story_id
        )
    )
  )
`

type DropConflictingAliasesParams struct {
	FromID   int64
	IntoName string
	IntoID   int64
}

func (q *Queries) DropConflictingAliases(ctx context.Context, arg DropConflictingAliasesParams) error {
	_, err := q.db.ExecContext(ctx, dropConflictingAliases, arg.FromID, arg.IntoName, arg.IntoID)
	return err
}

const getAlias = `-- name: GetAlias :one
SELECT
  a.id,
  a.product_id,
  p.name AS product_name,
  CAST(COALESCE(a.story_id, 0) AS INTEGER) AS story_id,
  COALESCE(c.name, '') AS story_name,
  CAST(COALESCE(a.retail_chain_id, 0) AS INTEGER) AS retail_chain_id,
  COALESCE(rc.name, '') AS retail_chain_name,
  a.alias
FROM product_aliases a
JOIN products p ON p.id = a.product_id
LEFT JOIN stories c ON c.id = a.story_id
LEFT JOIN retail_chains rc ON rc.id = a.retail_chain_id
WHERE a.id = ?
`

type GetAliasRow struct {
	ID              int64
	ProductID       int64
	ProductName     string
	StoryID         int64
	StoryName       string
	RetailChainID   int64
	RetailChainName string
	Alias           string
}

func (q *Queries) GetAlias(ctx context.Context, id int64) (GetAliasRow, error) {
	row := q.db.QueryRowContext(ctx, getAlias, id)
	var i GetAliasRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.StoryID,
		&i.StoryName,
		&i.RetailChainID,
		&i.RetailChainName,
		&i.Alias,
	)
	return i, err
}

const insertAlias = `-- name: InsertAlias :one
INSERT INTO product_aliases (product_id, story_id, retail_chain_id, alias)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertAliasParams struct {
	ProductID     int64
	StoryID       sql.NullInt64
	RetailChainID sql.NullInt64
	Alias         string
}

func (q *Queries) InsertAlias(ctx context.Context, arg InsertAliasParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAlias,
		arg.ProductID,
		arg.StoryID,
		arg.RetailChainID,
		arg.Alias,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAliases = `-- name: ListAliases :many
SELECT
  a.id,
  a.product_id,
  p.name AS product_name,
  CAST(COALESCE(a.story_id, 0) AS INTEGER) AS story_id,
  COALESCE(c.name, '') AS story_name,
  CAST(COALESCE(a.retail_chain_id, 0) AS INTEGER) AS retail_chain_id,
  COALESCE(rc.name, '') AS retail_chain_name,
  a.alias
FROM product_aliases a
JOIN products p ON p.id = a.product_id
LEFT JOIN stories c ON c.id = a.story_id
LEFT JOIN retail_chains rc ON rc.id = a.retail_chain_id
ORDER BY p.name COLLATE NOCASE, c.name COLLATE NOCASE, rc.name COLLATE NOCASE, a.alias COLLATE NOCASE, a.id
`

type ListAliasesRow struct {
	ID              int64
	ProductID       int64
	ProductName     string
	StoryID         int64
	StoryName       string
	RetailChainID   int64
	RetailChainName string
	Alias           string
}

func (q *Queries) ListAliases(ctx context.Context) ([]ListAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAliasesRow{}
	for rows.Next() {
		var i ListAliasesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.StoryID,
			&i.StoryName,
			&i.RetailChainID,
			&i.RetailChainName,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAliasesByProduct = `-- name: ListAliasesByProduct :many
SELECT
  a.id,
  a.product_id,
  p.name AS product_name,
  CAST(COALESCE(a.story_id, 0) AS INTEGER) AS story_id,
  COALESCE(c.name, '') AS story_name,
  CAST(COALESCE(a.retail_chain_id, 0) AS INTEGER) AS retail_chain_id,
  COALESCE(rc.name, '') AS retail_chain_name,
  a.alias
FROM product_aliases a
JOIN products p ON p.id = a.product_id
LEFT JOIN stories c ON c.id = a.story_id
LEFT JOIN retail_chains rc ON rc.id = a.retail_chain_id
WHERE a.product_id = ?
ORDER BY a.story_id IS NOT NULL, a.retail_chain_id IS NOT NULL, c.name COLLATE NOCASE, rc.name COLLATE NOCASE, a.alias COLLATE NOCASE, a.id
`

type ListAliasesByProductRow struct {
	ID              int64
	ProductID       int64
	ProductName     string
	StoryID         int64
	StoryName       string
	RetailChainID   int64
	RetailChainName string
	Alias           string
}

func (q *Queries) ListAliasesByProduct(ctx context.Context, productID int64) ([]ListAliasesByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listAliasesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAliasesByProductRow{}
	for rows.Next() {
		var i ListAliasesByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.StoryID,
			&i.StoryName,
			&i.RetailChainID,
			&i.RetailChainName,
			&i.Alias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productByChainAlias = `-- name: ProductByChainAlias :one
SELECT p.id, p.name, p.unit_id, u.name AS unit_name, p.image_path, p.created_at
FROM product_aliases a
JOIN products p ON p.id = a.product_id
JOIN units u ON u.id = p.unit_id
WHERE a.alias = ? COLLATE NOCASE AND a.retail_chain_id = ?
ORDER BY a.id
LIMIT 1
`

type ProductByChainAliasParams struct {
	Alias         string
	RetailChainID sql.NullInt64
}

type ProductByChainAliasRow struct {
	ID        int64
	Name      string
	UnitID    int64
	UnitName  string
	ImagePath sql.NullString
	CreatedAt string
}

func (q *Queries) ProductByChainAlias(ctx context.Context, arg ProductByChainAliasParams) (ProductByChainAliasRow, error) {
	row := q.db.QueryRowContext(ctx, productByChainAlias, arg.Alias, arg.RetailChainID)
	var i ProductByChainAliasRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnitID,
		&i.UnitName,
		&i.ImagePath,
		&i.CreatedAt,
	)
	return i, err
}

const productByGlobalAlias = `-- name: ProductByGlobalAlias :one
SELECT p.id, p.name, p.unit_id, u.name AS unit_name, p.image_path, p.created_at
FROM product_aliases a
JOIN products p ON p.id = a.product_id
JOIN units u ON u.id = p.unit_id
WHERE a.alias = ? COLLATE NOCASE AND a.story_id IS NULL AND a.retail_chain_id IS NULL
ORDER BY a.id
LIMIT 1
`

type ProductByGlobalAliasRow struct {
	ID        int64
	Name      string
	UnitID    int64
	UnitName  string
	ImagePath sql.NullString
	CreatedAt string
}

func (q *Queries) ProductByGlobalAlias(ctx context.Context, alias string) (ProductByGlobalAliasRow, error) {
	row := q.db.QueryRowContext(ctx, productByGlobalAlias, alias)
	var i ProductByGlobalAliasRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnitID,
		&i.UnitName,
		&i.ImagePath,
		&i.CreatedAt,
	)
	return i, err
}

const productByStoryAlias = `-- name: ProductByStoryAlias :one
SELECT p.id, p.name, p.unit_id, u.name AS unit_name, p.image_path, p.created_at
FROM product_aliases a
JOIN products p ON p.id = a.product_id
JOIN units u ON u.id = p.unit_id
WHERE a.alias = ? COLLATE NOCASE AND a.story_id = ?
ORDER BY a.id
LIMIT 1
`

type ProductByStoryAliasParams struct {
	Alias   string
	StoryID sql.NullInt64
}

type ProductByStoryAliasRow struct {
	ID        int64
	Name      string
	UnitID    int64
	UnitName  string
	ImagePath sql.NullString
	CreatedAt string
}

func (q *Queries) ProductByStoryAlias(ctx context.Context, arg ProductByStoryAliasParams) (ProductByStoryAliasRow, error) {
	row := q.db.QueryRowContext(ctx, productByStoryAlias, arg.Alias, arg.StoryID)
	var i ProductByStoryAliasRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnitID,
		&i.UnitName,
		&i.ImagePath,
		&i.CreatedAt,
	)
	return i, err
}

const reassignAliases = `-- name: ReassignAliases :exec
UPDATE product_aliases SET product_id = ?1 WHERE product_id = ?2
`

type ReassignAliasesParams struct {
	IntoID int64
	FromID int64
}

func (q *Queries) ReassignAliases(ctx context.Context, arg ReassignAliasesParams) error {
	_, err := q.db.ExecContext(ctx, reassignAliases, arg.IntoID, arg.FromID)
	return err
}

const updateAlias = `-- name: UpdateAlias :execrows
UPDATE product_aliases
SET product_id = ?, story_id = ?, retail_chain_id = ?, alias = ?
WHERE id = ?
`

type UpdateAliasParams struct {
	ProductID     int64
	StoryID       sql.NullInt64
	RetailChainID sql.NullInt64
	Alias         string
	ID            int64
}

func (q *Queries) UpdateAlias(ctx context.Context, arg UpdateAliasParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAlias,
		arg.ProductID,
		arg.StoryID,
		arg.RetailChainID,
		arg.Alias,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
