// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chains.sql

package sqlc

import (
	"context"
)

const countRetailChainsByID = `-- name: CountRetailChainsByID :one
SELECT COUNT(*) FROM retail_chains WHERE id = ?
`

func (q *Queries) CountRetailChainsByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRetailChainsByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRetailChain = `-- name: DeleteRetailChain :execrows
DELETE FROM retail_chains WHERE id = ?
`

func (q *Queries) DeleteRetailChain(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetailChain, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRetailChain = `-- name: GetRetailChain :one
SELECT
  rc.id,
  rc.name,
  rc.legal_name,
  rc.tax_id,
  CAST((SELECT COUNT(*) FROM stories s WHERE s.retail_chain_id = rc.id) AS INTEGER) AS story_count
FROM retail_chains rc
WHERE rc.id = ?
`

type GetRetailChainRow struct {
	ID         int64
	Name       string
	LegalName  string
	TaxID      string
	StoryCount int64
}

func (q *Queries) GetRetailChain(ctx context.Context, id int64) (GetRetailChainRow, error) {
	row := q.db.QueryRowContext(ctx, getRetailChain, id)
	var i GetRetailChainRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LegalName,
		&i.TaxID,
		&i.StoryCount,
	)
	return i, err
}

const insertRetailChain = `-- name: InsertRetailChain :one
INSERT INTO retail_chains (name, legal_name, tax_id)
VALUES (?, ?, ?)
RETURNING id
`

type InsertRetailChainParams struct {
	Name      string
	LegalName string
	TaxID     string
}

func (q *Queries) InsertRetailChain(ctx context.Context, arg InsertRetailChainParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRetailChain, arg.Name, arg.LegalName, arg.TaxID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRetailChains = `-- name: ListRetailChains :many
SELECT
  rc.id,
  rc.name,
  rc.legal_name,
  rc.tax_id,
  CAST((SELECT COUNT(*) FROM stories s WHERE s.retail_chain_id = rc.id) AS INTEGER) AS story_count
FROM retail_chains rc
ORDER BY rc.name COLLATE NOCASE, rc.id
`

type ListRetailChainsRow struct {
	ID         int64
	Name       string
	LegalName  string
	TaxID      string
	StoryCount int64
}

func (q *Queries) ListRetailChains(ctx context.Context) ([]ListRetailChainsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRetailChains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRetailChainsRow{}
	for rows.Next() {
		var i ListRetailChainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LegalName,
			&i.TaxID,
			&i.StoryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRetailChain = `-- name: UpdateRetailChain :execrows
UPDATE retail_chains
SET name = ?, legal_name = ?, tax_id = ?
WHERE id = ?
`

type UpdateRetailChainParams struct {
	Name      string
	LegalName string
	TaxID     string
	ID        int64
}

func (q *Queries) UpdateRetailChain(ctx context.Context, arg UpdateRetailChainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRetailChain,
		arg.Name,
		arg.LegalName,
		arg.TaxID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
