// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comparison_groups.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const countComparisonGroupsByID = `-- name: CountComparisonGroupsByID :one
SELECT COUNT(*) FROM comparison_groups WHERE id = ?
`

func (q *Queries) CountComparisonGroupsByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countComparisonGroupsByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComparisonGroupsByUnit = `-- name: CountComparisonGroupsByUnit :one
SELECT COUNT(*) FROM comparison_groups WHERE unit_id = ?
`

func (q *Queries) CountComparisonGroupsByUnit(ctx context.Context, unitID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countComparisonGroupsByUnit, unitID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteComparisonGroup = `-- name: DeleteComparisonGroup :execrows
DELETE FROM comparison_groups WHERE id = ?
`

func (q *Queries) DeleteComparisonGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteComparisonGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteComparisonGroupProducts = `-- name: DeleteComparisonGroupProducts :exec
DELETE FROM comparison_group_products WHERE group_id = ?
`

func (q *Queries) DeleteComparisonGroupProducts(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, deleteComparisonGroupProducts, groupID)
	return err
}

const deleteProductComparisonGroups = `-- name: DeleteProductComparisonGroups :exec
DELETE FROM comparison_group_products WHERE product_id = ?
`

func (q *Queries) DeleteProductComparisonGroups(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductComparisonGroups, productID)
	return err
}

const getComparisonGroup = `-- name: GetComparisonGroup :one
SELECT
  g.id,
  g.name,
  g.unit_id,
  u.name AS unit_name,
  g.created_at,
  CAST((SELECT COUNT(*) FROM comparison_group_products m WHERE m.group_id = g.id) AS INTEGER) AS product_count
FROM comparison_groups g
JOIN units u ON u.id = g.unit_id
WHERE g.id = ?
`

type GetComparisonGroupRow struct {
	ID           int64
	Name         string
	UnitID       int64
	UnitName     string
	CreatedAt    string
	ProductCount int64
}

func (q *Queries) GetComparisonGroup(ctx context.Context, id int64) (GetComparisonGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getComparisonGroup, id)
	var i GetComparisonGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnitID,
		&i.UnitName,
		&i.CreatedAt,
		&i.ProductCount,
	)
	return i, err
}

const insertComparisonGroup = `-- name: InsertComparisonGroup :one
INSERT INTO comparison_groups (name, unit_id, created_at)
VALUES (?, ?, ?)
RETURNING id
`

type InsertComparisonGroupParams struct {
	Name      string
	UnitID    int64
	CreatedAt string
}

func (q *Queries) InsertComparisonGroup(ctx context.Context, arg InsertComparisonGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertComparisonGroup, arg.Name, arg.UnitID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertComparisonGroupProduct = `-- name: InsertComparisonGroupProduct :exec
INSERT INTO comparison_group_products (group_id, product_id)
VALUES (?, ?)
`

type InsertComparisonGroupProductParams struct {
	GroupID   int64
	ProductID int64
}

func (q *Queries) InsertComparisonGroupProduct(ctx context.Context, arg InsertComparisonGroupProductParams) error {
	_, err := q.db.ExecContext(ctx, insertComparisonGroupProduct, arg.GroupID, arg.ProductID)
	return err
}

const listComparisonGroupProductIDs = `-- name: ListComparisonGroupProductIDs :many
SELECT product_id
FROM comparison_group_products
WHERE group_id = ?
ORDER BY product_id
`

func (q *Queries) ListComparisonGroupProductIDs(ctx context.Context, groupID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listComparisonGroupProductIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var product_id int64
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComparisonGroups = `-- name: ListComparisonGroups :many
SELECT
  g.id,
  g.name,
  g.unit_id,
  u.name AS unit_name,
  g.created_at,
  CAST((SELECT COUNT(*) FROM comparison_group_products m WHERE m.group_id = g.id) AS INTEGER) AS product_count
FROM comparison_groups g
JOIN units u ON u.id = g.unit_id
ORDER BY g.name COLLATE NOCASE, g.id
`

type ListComparisonGroupsRow struct {
	ID           int64
	Name         string
	UnitID       int64
	UnitName     string
	CreatedAt    string
	ProductCount int64
}

func (q *Queries) ListComparisonGroups(ctx context.Context) ([]ListComparisonGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComparisonGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComparisonGroupsRow{}
	for rows.Next() {
		var i ListComparisonGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnitID,
			&i.UnitName,
			&i.CreatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComparisonGroupsForProduct = `-- name: ListComparisonGroupsForProduct :many
SELECT
  g.id,
  g.name,
  g.unit_id,
  u.name AS unit_name,
  g.created_at,
  CAST((SELECT COUNT(*) FROM comparison_group_products m WHERE m.group_id = g.id) AS INTEGER) AS product_count
FROM comparison_group_products mine
JOIN comparison_groups g ON g.id = mine.group_id
JOIN units u ON u.id = g.unit_id
WHERE mine.product_id = ?
ORDER BY g.name COLLATE NOCASE, g.id
`

type ListComparisonGroupsForProductRow struct {
	ID           int64
	Name         string
	UnitID       int64
	UnitName     string
	CreatedAt    string
	ProductCount int64
}

func (q *Queries) ListComparisonGroupsForProduct(ctx context.Context, productID int64) ([]ListComparisonGroupsForProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listComparisonGroupsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComparisonGroupsForProductRow{}
	for rows.Next() {
		var i ListComparisonGroupsForProductRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnitID,
			&i.UnitName,
			&i.CreatedAt,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComparisonMembersForProduct = `-- name: ListComparisonMembersForProduct :many
SELECT
  g.id AS group_id,
  g.name AS group_name,
  g.unit_id AS group_unit_id,
  u.name AS group_unit_name,
  p.id AS product_id,
  p.name AS product_name,
  p.unit_id AS product_unit_id,
  c.factor AS conversion_factor
FROM comparison_group_products mine
JOIN comparison_groups g ON g.id = mine.group_id
JOIN units u ON u.id = g.unit_id
JOIN comparison_group_products m ON m.group_id = g.id
JOIN products p ON p.id = m.product_id
LEFT JOIN product_unit_conversions c
  ON c.product_id = p.id AND c.unit_id = g.unit_id
WHERE mine.product_id = ?
ORDER BY g.name COLLATE NOCASE, g.id, p.name COLLATE NOCASE, p.id
`

type ListComparisonMembersForProductRow struct {
	GroupID          int64
	GroupName        string
	GroupUnitID      int64
	GroupUnitName    string
	ProductID        int64
	ProductName      string
	ProductUnitID    int64
	ConversionFactor sql.NullString
}

func (q *Queries) ListComparisonMembersForProduct(ctx context.Context, productID int64) ([]ListComparisonMembersForProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listComparisonMembersForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComparisonMembersForProductRow{}
	for rows.Next() {
		var i ListComparisonMembersForProductRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.GroupUnitID,
			&i.GroupUnitName,
			&i.ProductID,
			&i.ProductName,
			&i.ProductUnitID,
			&i.ConversionFactor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasesForProductIDs = `-- name: ListPurchasesForProductIDs :many
SELECT
  p.id,
  p.product_id,
  CAST(COALESCE(p.story_id, 0) AS INTEGER) AS story_id,
  p.kind,
  CAST(COALESCE(p.receipt_id, 0) AS INTEGER) AS receipt_id,
  p.bought_on,
  p.quantity,
  p.amount,
  p.created_at
FROM purchases p
WHERE p.product_id IN (/*SLICE:product_ids*/?)
ORDER BY p.bought_on DESC, p.id DESC
`

type ListPurchasesForProductIDsRow struct {
	ID        int64
	ProductID int64
	StoryID   int64
	Kind      string
	ReceiptID int64
	BoughtOn  string
	Quantity  string
	Amount    string
	CreatedAt string
}

func (q *Queries) ListPurchasesForProductIDs(ctx context.Context, productIds []int64) ([]ListPurchasesForProductIDsRow, error) {
	query := listPurchasesForProductIDs
	var queryParams []interface{}
	if len(productIds) > 0 {
		for _, v := range productIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(productIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchasesForProductIDsRow{}
	for rows.Next() {
		var i ListPurchasesForProductIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StoryID,
			&i.Kind,
			&i.ReceiptID,
			&i.BoughtOn,
			&i.Quantity,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedGroupProducts = `-- name: ListRelatedGroupProducts :many
SELECT DISTINCT
  p.id,
  p.name,
  p.unit_id,
  u.name AS unit_name,
  p.image_path,
  p.created_at
FROM comparison_group_products mine
JOIN comparison_group_products m ON m.group_id = mine.group_id
JOIN products p ON p.id = m.product_id
JOIN units u ON u.id = p.unit_id
WHERE mine.product_id = ?1
  AND p.id != ?2
ORDER BY p.name COLLATE NOCASE, p.id
`

type ListRelatedGroupProductsParams struct {
	ProductID int64
	ExcludeID int64
}

type ListRelatedGroupProductsRow struct {
	ID        int64
	Name      string
	UnitID    int64
	UnitName  string
	ImagePath sql.NullString
	CreatedAt string
}

func (q *Queries) ListRelatedGroupProducts(ctx context.Context, arg ListRelatedGroupProductsParams) ([]ListRelatedGroupProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelatedGroupProducts, arg.ProductID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelatedGroupProductsRow{}
	for rows.Next() {
		var i ListRelatedGroupProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnitID,
			&i.UnitName,
			&i.ImagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignComparisonGroups = `-- name: ReassignComparisonGroups :exec
INSERT OR IGNORE INTO comparison_group_products (group_id, product_id)
SELECT m.group_id, ?1
FROM comparison_group_products m
WHERE m.product_id = ?2
`

type ReassignComparisonGroupsParams struct {
	IntoID int64
	FromID int64
}

func (q *Queries) ReassignComparisonGroups(ctx context.Context, arg ReassignComparisonGroupsParams) error {
	_, err := q.db.ExecContext(ctx, reassignComparisonGroups, arg.IntoID, arg.FromID)
	return err
}

const updateComparisonGroup = `-- name: UpdateComparisonGroup :execrows
UPDATE comparison_groups
SET name = ?, unit_id = ?
WHERE id = ?
`

type UpdateComparisonGroupParams struct {
	Name   string
	UnitID int64
	ID     int64
}

func (q *Queries) UpdateComparisonGroup(ctx context.Context, arg UpdateComparisonGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateComparisonGroup, arg.Name, arg.UnitID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
