// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversions.sql

package sqlc

import (
	"context"
)

const deleteProductConversions = `-- name: DeleteProductConversions :exec
DELETE FROM product_unit_conversions WHERE product_id = ?
`

func (q *Queries) DeleteProductConversions(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductConversions, productID)
	return err
}

const insertProductConversion = `-- name: InsertProductConversion :exec
INSERT INTO product_unit_conversions (product_id, unit_id, factor)
VALUES (?, ?, ?)
`

type InsertProductConversionParams struct {
	ProductID int64
	UnitID    int64
	Factor    string
}

func (q *Queries) InsertProductConversion(ctx context.Context, arg InsertProductConversionParams) error {
	_, err := q.db.ExecContext(ctx, insertProductConversion, arg.ProductID, arg.UnitID, arg.Factor)
	return err
}

const listAllProductConversions = `-- name: ListAllProductConversions :many
SELECT c.product_id, c.unit_id, u.name AS unit_name, c.factor
FROM product_unit_conversions c
JOIN units u ON u.id = c.unit_id
ORDER BY u.name COLLATE NOCASE
`

type ListAllProductConversionsRow struct {
	ProductID int64
	UnitID    int64
	UnitName  string
	Factor    string
}

func (q *Queries) ListAllProductConversions(ctx context.Context) ([]ListAllProductConversionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllProductConversions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProductConversionsRow{}
	for rows.Next() {
		var i ListAllProductConversionsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.UnitID,
			&i.UnitName,
			&i.Factor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductConversions = `-- name: ListProductConversions :many
SELECT c.unit_id, u.name AS unit_name, c.factor
FROM product_unit_conversions c
JOIN units u ON u.id = c.unit_id
WHERE c.product_id = ?
ORDER BY u.name COLLATE NOCASE
`

type ListProductConversionsRow struct {
	UnitID   int64
	UnitName string
	Factor   string
}

func (q *Queries) ListProductConversions(ctx context.Context, productID int64) ([]ListProductConversionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductConversions, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductConversionsRow{}
	for rows.Next() {
		var i ListProductConversionsRow
		if err := rows.Scan(&i.UnitID, &i.UnitName, &i.Factor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
