// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type ComparisonGroup struct {
	ID        int64
	Name      string
	UnitID    int64
	CreatedAt string
}

type ComparisonGroupProduct struct {
	GroupID   int64
	ProductID int64
}

type Product struct {
	ID        int64
	Name      string
	UnitID    int64
	ImagePath sql.NullString
	CreatedAt string
}

type ProductAlias struct {
	ID            int64
	ProductID     int64
	StoryID       sql.NullInt64
	RetailChainID sql.NullInt64
	Alias         string
}

type ProductUnitConversion struct {
	ProductID int64
	UnitID    int64
	Factor    string
}

type Purchase struct {
	ID        int64
	ProductID int64
	StoryID   sql.NullInt64
	BoughtOn  string
	Quantity  string
	Amount    string
	CreatedAt string
	Kind      string
	ReceiptID sql.NullInt64
}

type Receipt struct {
	ID           int64
	ImagePath    string
	RawResponse  string
	Status       string
	CreatedAt    string
	ErrorMessage string
}

type RetailChain struct {
	ID        int64
	Name      string
	LegalName string
	TaxID     string
}

type Setting struct {
	Key   string
	Value string
}

type Story struct {
	ID              int64
	Name            string
	StreetName      string
	BuildingNumber  string
	ApartmentNumber string
	PostalCode      string
	City            string
	RetailChainID   sql.NullInt64
	ExternalID      string
}

type Unit struct {
	ID   int64
	Name string
}
