// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countProductsByID = `-- name: CountProductsByID :one
SELECT COUNT(*) FROM products WHERE id = ?
`

func (q *Queries) CountProductsByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByName = `-- name: CountProductsByName :one
SELECT COUNT(*) FROM products WHERE name = ? COLLATE NOCASE
`

func (q *Queries) CountProductsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByNameExcept = `-- name: CountProductsByNameExcept :one
SELECT COUNT(*) FROM products WHERE name = ? COLLATE NOCASE AND id != ?
`

type CountProductsByNameExceptParams struct {
	Name string
	ID   int64
}

func (q *Queries) CountProductsByNameExcept(ctx context.Context, arg CountProductsByNameExceptParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByNameExcept, arg.Name, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const findProductByName = `-- name: FindProductByName :one
SELECT p.id, p.name, p.unit_id, u.name AS unit_name, p.image_path, p.created_at
FROM products p
JOIN units u ON u.id = p.unit_id
WHERE p.name = ? COLLATE NOCASE
ORDER BY p.id
LIMIT 1
`

type FindProductByNameRow struct {
	ID        int64
	Name      string
	UnitID    int64
	UnitName  string
	ImagePath sql.NullString
	CreatedAt string
}

func (q *Queries) FindProductByName(ctx context.Context, name string) (FindProductByNameRow, error) {
	row := q.db.QueryRowContext(ctx, findProductByName, name)
	var i FindProductByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnitID,
		&i.UnitName,
		&i.ImagePath,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT p.id, p.name, p.unit_id, u.name AS unit_name, p.image_path, p.created_at
FROM products p
JOIN units u ON u.id = p.unit_id
WHERE p.id = ?
`

type GetProductRow struct {
	ID        int64
	Name      string
	UnitID    int64
	UnitName  string
	ImagePath sql.NullString
	CreatedAt string
}

func (q *Queries) GetProduct(ctx context.Context, id int64) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UnitID,
		&i.UnitName,
		&i.ImagePath,
		&i.CreatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (name, unit_id, image_path, created_at)
VALUES (?, ?, ?, ?)
RETURNING id
`

type InsertProductParams struct {
	Name      string
	UnitID    int64
	ImagePath sql.NullString
	CreatedAt string
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.Name,
		arg.UnitID,
		arg.ImagePath,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.name, p.unit_id, u.name AS unit_name, p.image_path, p.created_at
FROM products p
JOIN units u ON u.id = p.unit_id
ORDER BY p.name COLLATE NOCASE
`

type ListProductsRow struct {
	ID        int64
	Name      string
	UnitID    int64
	UnitName  string
	ImagePath sql.NullString
	CreatedAt string
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UnitID,
			&i.UnitName,
			&i.ImagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE products
SET name = ?, unit_id = ?, image_path = ?
WHERE id = ?
`

type UpdateProductParams struct {
	Name      string
	UnitID    int64
	ImagePath sql.NullString
	ID        int64
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.UnitID,
		arg.ImagePath,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProductImage = `-- name: UpdateProductImage :exec
UPDATE products SET image_path = ? WHERE id = ?
`

type UpdateProductImageParams struct {
	ImagePath sql.NullString
	ID        int64
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error {
	_, err := q.db.ExecContext(ctx, updateProductImage, arg.ImagePath, arg.ID)
	return err
}

const updateProductUnit = `-- name: UpdateProductUnit :exec
UPDATE products SET unit_id = ? WHERE id = ?
`

type UpdateProductUnitParams struct {
	UnitID int64
	ID     int64
}

func (q *Queries) UpdateProductUnit(ctx context.Context, arg UpdateProductUnitParams) error {
	_, err := q.db.ExecContext(ctx, updateProductUnit, arg.UnitID, arg.ID)
	return err
}
