// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchases.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deletePurchase = `-- name: DeletePurchase :execrows
DELETE FROM purchases WHERE id = ?
`

func (q *Queries) DeletePurchase(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePurchase, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPurchase = `-- name: GetPurchase :one
SELECT
  p.id,
  p.product_id,
  CAST(COALESCE(p.story_id, 0) AS INTEGER) AS story_id,
  p.kind,
  CAST(COALESCE(p.receipt_id, 0) AS INTEGER) AS receipt_id,
  p.bought_on,
  p.quantity,
  p.amount,
  p.created_at
FROM purchases p
WHERE p.id = ?
`

type GetPurchaseRow struct {
	ID        int64
	ProductID int64
	StoryID   int64
	Kind      string
	ReceiptID int64
	BoughtOn  string
	Quantity  string
	Amount    string
	CreatedAt string
}

func (q *Queries) GetPurchase(ctx context.Context, id int64) (GetPurchaseRow, error) {
	row := q.db.QueryRowContext(ctx, getPurchase, id)
	var i GetPurchaseRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.StoryID,
		&i.Kind,
		&i.ReceiptID,
		&i.BoughtOn,
		&i.Quantity,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const insertPurchase = `-- name: InsertPurchase :one
INSERT INTO purchases (product_id, story_id, kind, receipt_id, bought_on, quantity, amount, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertPurchaseParams struct {
	ProductID int64
	StoryID   sql.NullInt64
	Kind      string
	ReceiptID sql.NullInt64
	BoughtOn  string
	Quantity  string
	Amount    string
	CreatedAt string
}

func (q *Queries) InsertPurchase(ctx context.Context, arg InsertPurchaseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPurchase,
		arg.ProductID,
		arg.StoryID,
		arg.Kind,
		arg.ReceiptID,
		arg.BoughtOn,
		arg.Quantity,
		arg.Amount,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPurchaseAmounts = `-- name: ListPurchaseAmounts :many
SELECT product_id, bought_on, amount
FROM purchases
WHERE kind = ?
`

type ListPurchaseAmountsRow struct {
	ProductID int64
	BoughtOn  string
	Amount    string
}

func (q *Queries) ListPurchaseAmounts(ctx context.Context, kind string) ([]ListPurchaseAmountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseAmounts, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseAmountsRow{}
	for rows.Next() {
		var i ListPurchaseAmountsRow
		if err := rows.Scan(&i.ProductID, &i.BoughtOn, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasesByProduct = `-- name: ListPurchasesByProduct :many
SELECT
  p.id,
  p.product_id,
  CAST(COALESCE(p.story_id, 0) AS INTEGER) AS story_id,
  p.kind,
  CAST(COALESCE(p.receipt_id, 0) AS INTEGER) AS receipt_id,
  p.bought_on,
  p.quantity,
  p.amount,
  p.created_at
FROM purchases p
WHERE p.product_id = ?
ORDER BY p.bought_on DESC, p.id DESC
`

type ListPurchasesByProductRow struct {
	ID        int64
	ProductID int64
	StoryID   int64
	Kind      string
	ReceiptID int64
	BoughtOn  string
	Quantity  string
	Amount    string
	CreatedAt string
}

func (q *Queries) ListPurchasesByProduct(ctx context.Context, productID int64) ([]ListPurchasesByProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchasesByProductRow{}
	for rows.Next() {
		var i ListPurchasesByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StoryID,
			&i.Kind,
			&i.ReceiptID,
			&i.BoughtOn,
			&i.Quantity,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasesByProductAsc = `-- name: ListPurchasesByProductAsc :many
SELECT
  p.id,
  p.product_id,
  CAST(COALESCE(p.story_id, 0) AS INTEGER) AS story_id,
  p.kind,
  CAST(COALESCE(p.receipt_id, 0) AS INTEGER) AS receipt_id,
  p.bought_on,
  p.quantity,
  p.amount,
  p.created_at
FROM purchases p
WHERE p.product_id = ?
ORDER BY p.id
`

type ListPurchasesByProductAscRow struct {
	ID        int64
	ProductID int64
	StoryID   int64
	Kind      string
	ReceiptID int64
	BoughtOn  string
	Quantity  string
	Amount    string
	CreatedAt string
}

func (q *Queries) ListPurchasesByProductAsc(ctx context.Context, productID int64) ([]ListPurchasesByProductAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasesByProductAsc, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchasesByProductAscRow{}
	for rows.Next() {
		var i ListPurchasesByProductAscRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StoryID,
			&i.Kind,
			&i.ReceiptID,
			&i.BoughtOn,
			&i.Quantity,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchasesByReceipt = `-- name: ListPurchasesByReceipt :many
SELECT
  p.id,
  p.product_id,
  CAST(COALESCE(p.story_id, 0) AS INTEGER) AS story_id,
  p.kind,
  CAST(COALESCE(p.receipt_id, 0) AS INTEGER) AS receipt_id,
  p.bought_on,
  p.quantity,
  p.amount,
  p.created_at,
  pr.name AS product_name,
  u.name AS unit_name,
  pr.image_path
FROM purchases p
JOIN products pr ON pr.id = p.product_id
JOIN units u ON u.id = pr.unit_id
WHERE p.receipt_id = ?
ORDER BY p.id
`

type ListPurchasesByReceiptRow struct {
	ID          int64
	ProductID   int64
	StoryID     int64
	Kind        string
	ReceiptID   int64
	BoughtOn    string
	Quantity    string
	Amount      string
	CreatedAt   string
	ProductName string
	UnitName    string
	ImagePath   sql.NullString
}

func (q *Queries) ListPurchasesByReceipt(ctx context.Context, receiptID sql.NullInt64) ([]ListPurchasesByReceiptRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchasesByReceipt, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchasesByReceiptRow{}
	for rows.Next() {
		var i ListPurchasesByReceiptRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.StoryID,
			&i.Kind,
			&i.ReceiptID,
			&i.BoughtOn,
			&i.Quantity,
			&i.Amount,
			&i.CreatedAt,
			&i.ProductName,
			&i.UnitName,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignPurchases = `-- name: ReassignPurchases :exec
UPDATE purchases SET product_id = ?1 WHERE product_id = ?2
`

type ReassignPurchasesParams struct {
	IntoID int64
	FromID int64
}

func (q *Queries) ReassignPurchases(ctx context.Context, arg ReassignPurchasesParams) error {
	_, err := q.db.ExecContext(ctx, reassignPurchases, arg.IntoID, arg.FromID)
	return err
}

const updatePurchase = `-- name: UpdatePurchase :execrows
UPDATE purchases
SET story_id = ?, kind = ?, bought_on = ?, quantity = ?, amount = ?
WHERE id = ?
`

type UpdatePurchaseParams struct {
	StoryID  sql.NullInt64
	Kind     string
	BoughtOn string
	Quantity string
	Amount   string
	ID       int64
}

func (q *Queries) UpdatePurchase(ctx context.Context, arg UpdatePurchaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePurchase,
		arg.StoryID,
		arg.Kind,
		arg.BoughtOn,
		arg.Quantity,
		arg.Amount,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePurchaseQuantity = `-- name: UpdatePurchaseQuantity :exec
UPDATE purchases SET quantity = ? WHERE id = ?
`

type UpdatePurchaseQuantityParams struct {
	Quantity string
	ID       int64
}

func (q *Queries) UpdatePurchaseQuantity(ctx context.Context, arg UpdatePurchaseQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updatePurchaseQuantity, arg.Quantity, arg.ID)
	return err
}

const updatePurchasesVisitByReceipt = `-- name: UpdatePurchasesVisitByReceipt :exec
UPDATE purchases SET story_id = ?, bought_on = ? WHERE receipt_id = ?
`

type UpdatePurchasesVisitByReceiptParams struct {
	StoryID   sql.NullInt64
	BoughtOn  string
	ReceiptID sql.NullInt64
}

func (q *Queries) UpdatePurchasesVisitByReceipt(ctx context.Context, arg UpdatePurchasesVisitByReceiptParams) error {
	_, err := q.db.ExecContext(ctx, updatePurchasesVisitByReceipt, arg.StoryID, arg.BoughtOn, arg.ReceiptID)
	return err
}
