// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package sqlc

import (
	"context"
)

const failReceipt = `-- name: FailReceipt :execrows
UPDATE receipts
SET status = ?, error_message = ?
WHERE id = ? AND status = ?
`

type FailReceiptParams struct {
	Status       string
	ErrorMessage string
	ID           int64
	Status_2     string
}

func (q *Queries) FailReceipt(ctx context.Context, arg FailReceiptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failReceipt,
		arg.Status,
		arg.ErrorMessage,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, image_path, raw_response, status, created_at, error_message, source, external_id
FROM receipts
WHERE id = ?
`

func (q *Queries) GetReceipt(ctx context.Context, id int64) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceipt, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.ImagePath,
		&i.RawResponse,
		&i.Status,
		&i.CreatedAt,
		&i.ErrorMessage,
		&i.Source,
		&i.ExternalID,
	)
	return i, err
}

const insertReceipt = `-- name: InsertReceipt :one
INSERT INTO receipts (image_path, raw_response, status, error_message, created_at, source, external_id)
VALUES (?, '', ?, '', ?, ?, ?)
RETURNING id
`

type InsertReceiptParams struct {
	ImagePath  string
	Status     string
	CreatedAt  string
	Source     string
	ExternalID string
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertReceipt,
		arg.ImagePath,
		arg.Status,
		arg.CreatedAt,
		arg.Source,
		arg.ExternalID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listReceiptExternalIDs = `-- name: ListReceiptExternalIDs :many
SELECT external_id FROM receipts
WHERE source = ? AND external_id != ''
`

func (q *Queries) ListReceiptExternalIDs(ctx context.Context, source string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listReceiptExternalIDs, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var externalID string
		if err := rows.Scan(&externalID); err != nil {
			return nil, err
		}
		items = append(items, externalID)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReceiptIDs = `-- name: ListPendingReceiptIDs :many
SELECT id FROM receipts WHERE status = ? ORDER BY id
`

func (q *Queries) ListPendingReceiptIDs(ctx context.Context, status string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPendingReceiptIDs, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceipts = `-- name: ListReceipts :many
SELECT id, image_path, status, error_message, created_at
FROM receipts
ORDER BY id DESC
`

type ListReceiptsRow struct {
	ID           int64
	ImagePath    string
	Status       string
	ErrorMessage string
	CreatedAt    string
}

func (q *Queries) ListReceipts(ctx context.Context) ([]ListReceiptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReceiptsRow{}
	for rows.Next() {
		var i ListReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.ImagePath,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReceiptMigrated = `-- name: MarkReceiptMigrated :exec
UPDATE receipts
SET status = ?, raw_response = ?
WHERE id = ?
`

type MarkReceiptMigratedParams struct {
	Status      string
	RawResponse string
	ID          int64
}

func (q *Queries) MarkReceiptMigrated(ctx context.Context, arg MarkReceiptMigratedParams) error {
	_, err := q.db.ExecContext(ctx, markReceiptMigrated, arg.Status, arg.RawResponse, arg.ID)
	return err
}

const requeueReceipt = `-- name: RequeueReceipt :execrows
UPDATE receipts
SET status = ?, error_message = ''
WHERE id = ? AND status = ?
`

type RequeueReceiptParams struct {
	Status   string
	ID       int64
	Status_2 string
}

func (q *Queries) RequeueReceipt(ctx context.Context, arg RequeueReceiptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueReceipt, arg.Status, arg.ID, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveAIResponse = `-- name: SaveAIResponse :execrows
UPDATE receipts
SET raw_response = ?, status = ?, error_message = ''
WHERE id = ? AND status IN (?, ?)
`

type SaveAIResponseParams struct {
	RawResponse string
	Status      string
	ID          int64
	Status_2    string
	Status_3    string
}

func (q *Queries) SaveAIResponse(ctx context.Context, arg SaveAIResponseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveAIResponse,
		arg.RawResponse,
		arg.Status,
		arg.ID,
		arg.Status_2,
		arg.Status_3,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateReceiptJSON = `-- name: UpdateReceiptJSON :execrows
UPDATE receipts
SET raw_response = ?
WHERE id = ? AND status = ?
`

type UpdateReceiptJSONParams struct {
	RawResponse string
	ID          int64
	Status      string
}

func (q *Queries) UpdateReceiptJSON(ctx context.Context, arg UpdateReceiptJSONParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateReceiptJSON, arg.RawResponse, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateReceiptRaw = `-- name: UpdateReceiptRaw :exec
UPDATE receipts SET raw_response = ? WHERE id = ?
`

type UpdateReceiptRawParams struct {
	RawResponse string
	ID          int64
}

func (q *Queries) UpdateReceiptRaw(ctx context.Context, arg UpdateReceiptRawParams) error {
	_, err := q.db.ExecContext(ctx, updateReceiptRaw, arg.RawResponse, arg.ID)
	return err
}
