// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countStoriesByID = `-- name: CountStoriesByID :one
SELECT COUNT(*) FROM stories WHERE id = ?
`

func (q *Queries) CountStoriesByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStoriesByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStory = `-- name: DeleteStory :execrows
DELETE FROM stories WHERE id = ?
`

func (q *Queries) DeleteStory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getStory = `-- name: GetStory :one
SELECT
  c.id,
  c.name,
  c.street_name,
  c.building_number,
  c.apartment_number,
  c.postal_code,
  c.city,
  c.external_id,
  CAST(COALESCE(c.retail_chain_id, 0) AS INTEGER) AS retail_chain_id,
  COALESCE(rc.name, '') AS retail_chain_name,
  CAST(COUNT(p.id) AS INTEGER) AS purchase_count
FROM stories c
LEFT JOIN retail_chains rc ON rc.id = c.retail_chain_id
LEFT JOIN purchases p ON p.story_id = c.id
WHERE c.id = ?
GROUP BY c.id
`

type GetStoryRow struct {
	ID              int64
	Name            string
	StreetName      string
	BuildingNumber  string
	ApartmentNumber string
	PostalCode      string
	City            string
	ExternalID      string
	RetailChainID   int64
	RetailChainName string
	PurchaseCount   int64
}

func (q *Queries) GetStory(ctx context.Context, id int64) (GetStoryRow, error) {
	row := q.db.QueryRowContext(ctx, getStory, id)
	var i GetStoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StreetName,
		&i.BuildingNumber,
		&i.ApartmentNumber,
		&i.PostalCode,
		&i.City,
		&i.ExternalID,
		&i.RetailChainID,
		&i.RetailChainName,
		&i.PurchaseCount,
	)
	return i, err
}

const getStoryRetailChainID = `-- name: GetStoryRetailChainID :one
SELECT retail_chain_id FROM stories WHERE id = ?
`

func (q *Queries) GetStoryRetailChainID(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getStoryRetailChainID, id)
	var retail_chain_id sql.NullInt64
	err := row.Scan(&retail_chain_id)
	return retail_chain_id, err
}

const insertStory = `-- name: InsertStory :one
INSERT INTO stories (
  name, street_name, building_number, apartment_number, postal_code, city, external_id, retail_chain_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertStoryParams struct {
	Name            string
	StreetName      string
	BuildingNumber  string
	ApartmentNumber string
	PostalCode      string
	City            string
	ExternalID      string
	RetailChainID   sql.NullInt64
}

func (q *Queries) InsertStory(ctx context.Context, arg InsertStoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertStory,
		arg.Name,
		arg.StreetName,
		arg.BuildingNumber,
		arg.ApartmentNumber,
		arg.PostalCode,
		arg.City,
		arg.ExternalID,
		arg.RetailChainID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listStories = `-- name: ListStories :many
SELECT
  c.id,
  c.name,
  c.street_name,
  c.building_number,
  c.apartment_number,
  c.postal_code,
  c.city,
  c.external_id,
  CAST(COALESCE(c.retail_chain_id, 0) AS INTEGER) AS retail_chain_id,
  COALESCE(rc.name, '') AS retail_chain_name,
  CAST(COUNT(p.id) AS INTEGER) AS purchase_count
FROM stories c
LEFT JOIN retail_chains rc ON rc.id = c.retail_chain_id
LEFT JOIN purchases p ON p.story_id = c.id
GROUP BY c.id
ORDER BY c.name COLLATE NOCASE, c.id
`

type ListStoriesRow struct {
	ID              int64
	Name            string
	StreetName      string
	BuildingNumber  string
	ApartmentNumber string
	PostalCode      string
	City            string
	ExternalID      string
	RetailChainID   int64
	RetailChainName string
	PurchaseCount   int64
}

func (q *Queries) ListStories(ctx context.Context) ([]ListStoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStoriesRow{}
	for rows.Next() {
		var i ListStoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StreetName,
			&i.BuildingNumber,
			&i.ApartmentNumber,
			&i.PostalCode,
			&i.City,
			&i.ExternalID,
			&i.RetailChainID,
			&i.RetailChainName,
			&i.PurchaseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStory = `-- name: UpdateStory :execrows
UPDATE stories
SET name = ?, street_name = ?, building_number = ?, apartment_number = ?, postal_code = ?, city = ?, external_id = ?, retail_chain_id = ?
WHERE id = ?
`

type UpdateStoryParams struct {
	Name            string
	StreetName      string
	BuildingNumber  string
	ApartmentNumber string
	PostalCode      string
	City            string
	ExternalID      string
	RetailChainID   sql.NullInt64
	ID              int64
}

func (q *Queries) UpdateStory(ctx context.Context, arg UpdateStoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStory,
		arg.Name,
		arg.StreetName,
		arg.BuildingNumber,
		arg.ApartmentNumber,
		arg.PostalCode,
		arg.City,
		arg.ExternalID,
		arg.RetailChainID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
