// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"
)

const countUnitsByID = `-- name: CountUnitsByID :one
SELECT COUNT(*) FROM units WHERE id = ?
`

func (q *Queries) CountUnitsByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnitsByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUnit = `-- name: DeleteUnit :execrows
DELETE FROM units
WHERE id = ?
`

func (q *Queries) DeleteUnit(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnit, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findUnitByName = `-- name: FindUnitByName :one
SELECT
  u.id,
  u.name,
  CAST(
    (SELECT COUNT(*) FROM products p WHERE p.unit_id = u.id)
    + (SELECT COUNT(*) FROM product_unit_conversions c WHERE c.unit_id = u.id)
    AS INTEGER
  ) AS product_count
FROM units u
WHERE u.name = ? COLLATE NOCASE
`

type FindUnitByNameRow struct {
	ID           int64
	Name         string
	ProductCount int64
}

func (q *Queries) FindUnitByName(ctx context.Context, name string) (FindUnitByNameRow, error) {
	row := q.db.QueryRowContext(ctx, findUnitByName, name)
	var i FindUnitByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.ProductCount)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT
  u.id,
  u.name,
  CAST(
    (SELECT COUNT(*) FROM products p WHERE p.unit_id = u.id)
    + (SELECT COUNT(*) FROM product_unit_conversions c WHERE c.unit_id = u.id)
    AS INTEGER
  ) AS product_count
FROM units u
WHERE u.id = ?
`

type GetUnitRow struct {
	ID           int64
	Name         string
	ProductCount int64
}

func (q *Queries) GetUnit(ctx context.Context, id int64) (GetUnitRow, error) {
	row := q.db.QueryRowContext(ctx, getUnit, id)
	var i GetUnitRow
	err := row.Scan(&i.ID, &i.Name, &i.ProductCount)
	return i, err
}

const insertUnit = `-- name: InsertUnit :one
INSERT INTO units (name)
VALUES (?)
RETURNING id
`

func (q *Queries) InsertUnit(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertUnit, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listUnits = `-- name: ListUnits :many
SELECT
  u.id,
  u.name,
  CAST(
    (SELECT COUNT(*) FROM products p WHERE p.unit_id = u.id)
    + (SELECT COUNT(*) FROM product_unit_conversions c WHERE c.unit_id = u.id)
    AS INTEGER
  ) AS product_count
FROM units u
ORDER BY u.name COLLATE NOCASE
`

type ListUnitsRow struct {
	ID           int64
	Name         string
	ProductCount int64
}

func (q *Queries) ListUnits(ctx context.Context) ([]ListUnitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitsRow{}
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ProductCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :execrows
UPDATE units
SET name = ?
WHERE id = ?
`

type UpdateUnitParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUnit, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
